### ISSUE TITLE
Implement Deserializer<'_> / IntoDeserializer for Value<'_>

### ISSUE THREAD

**Issue by A-Manning** [PSeitz/serde_json_borrow#10]
Would it be possible to implement [`serde::Deserializer<'ctx>`](https://docs.rs/serde/latest/serde/trait.Deserializer.html) / [`serde::de::IntoDeserializer`](https://docs.rs/serde/latest/serde/de/trait.IntoDeserializer.html) for [`serde_json_borrow::Value<'ctx>`](https://docs.rs/serde_json_borrow/latest/serde_json_borrow/enum.Value.html)?

`serde_json_borrow::Value` is often useful as an intermediate value when deserializing, and so it would be nice to be able to deserialize from a `serde_json_borrow::Value` in the same way that one can from a `serde_json::Value`. Note that `serde_json::Value` implements `serde::Deserializer` and `serde::de::IntoDeserializer`, and `serde_json` also provides the helpful [`serde_json::from_value`](https://docs.rs/serde_json/latest/serde_json/fn.from_value.html) function to deserialize  from a `serde_json::Value`.

**Comment by PSeitz** [comment]
Sorry for the late reply. 
I think that would be a good addition to reach feature parity. I would accept an PR for that.

And just as a heads up, I consider removing the limitation that keys in objects are not allowed to have any JSON escaping characters. (maybe as a feature flag)

**Comment by ssddOnTop** [comment]
> And just as a heads up, I consider removing the limitation that keys in objects are not allowed to have any JSON escaping characters. (maybe as a feature flag)

can you give an example of some failing case

**Comment by PSeitz** [comment]
released with `0.7.0`
