### ISSUE TITLE
Implement `ToOwned<Owned = serde_json::Value>` for `serde_json_borrow::Value`

### ISSUE THREAD

**Issue by tqwewe** [PSeitz/serde_json_borrow#2]
This would allow me to use `Cow<'a, serde_json_borrow::Value>`, which is useful in my case for `HashMap<'static str, Cow<'static, serde_json_borrow::Value>`.

**Comment by tqwewe** [comment]
Nevermind, it seems like its not possible since we cannot implement Borrow for serde_json::Value.

**Comment by PSeitz** [comment]
You should be able to convert it via `.into()` into `serde_json::Value`

https://github.com/PSeitz/serde_json_borrow/blob/main/src/value.rs#L382
